### ISSUE TITLE
Deliverable: SRS

### ISSUE THREAD

**Issue by adampodolak** [ausbennett/mes-finance-platform#20]
**Tasks**

- [x] Adam Podolak: Sections 9 - 11, 18
- [x] Christian Petricca: Sections 1 - 8
- [x] Evan Sturmey: Sections 15 - 17
- [x] Austin Bennett: Sections 19 - 26
- [x] Jacob Kish: Sections 12 - 14
